apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-api
  namespace: dev
spec:
  selector:
    matchLabels:
      app: auth-api
  template:
    metadata:
      labels:
        app: auth-api
    spec:
      containers:
        - name: auth-api
          image: thanapongsj/tcc-auth-service:d9109968f1855b7fdaa53a12fd5f1278b5bac6a7
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 3000
