apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-api
  namespace: dev
spec:
  selector:
    matchLabels:
      app: auth-api
  template:
    metadata:
      labels:
        app: auth-api
    spec:
      containers:
        - name: auth-api
          image: thanapongsj/tcc-auth-service:f1b63dd3eda02ce0b11f5e07d347025002581ee2
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 3000
